version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: calendar_mysql
    restart: always
    environment:
      MYSQL_DATABASE: calendar
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: 