version: '3.8'

services:
  golendar_db:
    image: mysql:8.0
    container_name: golendar_db
    restart: always
    environment:
      MYSQL_DATABASE: calendar
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  golendar_app:
    build: .
    container_name: golendar_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=golendar_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=calendar
    depends_on:
      golendar_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db_data: 